import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es" className=' scroll-smooth scroll-pt-16'>
      <body className='bg-background font-fira '>{children}</body>
    </html>
  )
}
